---
- name: Ensure Docker service has started
  service:
    name: docker
    state: started

- name: Register Master
  command: "docker swarm init --listen-addr {{docker_master_ip}}:{{docker_master_port}}"
  register: result
  until: result.stdout.find("Swarm initialized") != -1
  retries: 10
  delay: 15
