---
- name: Ensure Docker service has started
  service:
    name: docker
    state: started
  become: true

- name: Register Node
  command: "docker swarm join {{docker_master_ip}}:{{docker_master_port}}"
  register: result
  until: result.stdout.find("joined a Swarm") != -1
  retries: 5
  delay: 5
