---
- name: Ensure Docker service has started
  service:
    name: docker
    state: started

- name: Register Node
  shell: "docker swarm join {{docker_master_ip}}:{{docker_master_port}}"
  register: result
  until: result.stdout.find("joined a Swarm") != -1
  retries: 50
  delay: 15
