---
- name: Install pre packages
  apt:
    name: "{{item}}"
    state: installed
  with_items: "{{pre_packages}}"

- name: Alternative | Add Docker repository key
  shell: "curl -sSL {{docker_apt_url}} | sudo apt-key add -"

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{docker_apt_repo}}"
    mode: '644'
    update_cache: yes
    state: present

- name: Update apt cache
  apt: update_cache=yes

- name: Install post packages
  apt:
    name: "{{item}}"
    state: installed
  with_items: "{{post_packages}}"

- name: Add users to the docker group
  user:
    name: "{{ansible_ssh_user}}"
    groups: docker
    append: yes

- name: Download Docker 1.12
  shell: "wget {{docker_112_url}} -O {{docker_tmp_dir}}.tgz"

- name: untar Docker 1.12
  unarchive:
    src: "{{docker_tmp_dir}}.tgz"
    dest: /root
    copy: no

- name: Remove tarball
  file:
    name: "{{docker_tmp_dir}}.tgz"
    state: absent

- name: Put new binaries in place
  shell: mv "{{docker_tmp_dir}}"/* /usr/bin

- name: Restart Docker service
  service:
    name: docker
    state: restarted
